=== theComputeKid/scrapper/utils/schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "utils/schema.json",
    "name": "scrapper schema",
    "description": "Describes C++ functions.",
    "type": "object",
    "properties": {
        "includes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "linkage-macro": {
            "type": "string"
        },
        "suffix-mapping": {
            "type": "object"
        },
        "functions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "combination": {
                        "type": "string",
                        "enum": [
                            "all",
                            "fixed"
                        ]
                    },
                    "templates": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "types": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "required": [
                                "name",
                                "types"
                            ]
                        }
                    },
                    "parameters": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "const": {
                                    "type": "boolean"
                                },
                                "pointer": {
                                    "type": "boolean"
                                },
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "name",
                                "type",
                                "const",
                                "pointer"
                            ]
                        }
                    }
                },
                "required": [
                    "name",
                    "combination",
                    "templates",
                    "return"
                ]
            }
        }
    },
    "required": [
        "$schema",
        "linkage-macro",
        "functions"
    ]
}

=== theComputeKid/scrapper/examples/advanced.json
{
    "$schema": "https://raw.githubusercontent.com/theComputeKid/scrapper/main/utils/schema.json",
    "includes": [
        "<stdint.h>"
    ],
    "linkage-macro": "MY_ADVANCED_PROJECT",
    "suffix-mapping": {
        "float": "fp32",
        "float _Complex": "cfp32"
    },
    "functions": [
        {
            "name": "multiply",
            "combination": "all",
            "description": "Multiplies two values.",
            "templates": [
                {
                    "name": "T1",
                    "types": [
                        "float _Complex",
                        "double _Complex"
                    ]
                },
                {
                    "name": "T2",
                    "types": [
                        "int32_t",
                        "float",
                        "double"
                    ]
                }
            ],
            "parameters": [
                {
                    "name": "left",
                    "type": "T1",
                    "const": true,
                    "pointer": true,
                    "description": "The left value to be added."
                },
                {
                    "name": "right",
                    "type": "T2",
                    "const": true,
                    "pointer": true,
                    "description": "The right value to be added."
                },
                {
                    "name": "result",
                    "type": "T1",
                    "const": false,
                    "pointer": true
                }
            ],
            "return": {
                "type": "int",
                "const": false,
                "pointer": false,
                "description": "The status of the computation."
            }
        },
        {
            "name": "divide",
            "combination": "fixed",
            "templates": [
                {
                    "name": "T1",
                    "types": [
                        "float",
                        "int8_t"
                    ]
                },
                {
                    "name": "T2",
                    "types": [
                        "double",
                        "int16_t"
                    ]
                }
            ],
            "parameters": [
                {
                    "name": "left",
                    "type": "T1",
                    "const": true,
                    "pointer": false
                },
                {
                    "name": "right",
                    "type": "T2",
                    "const": true,
                    "pointer": false
                }
            ],
            "return": {
                "type": "T2",
                "const": false,
                "pointer": false
            }
        }
    ]
}
